project_id = "slqwrxkqqphpkkhojjho"

[functions.admin-reset-password]
verify_jwt = false

[functions.import-providers]
verify_jwt = false

[functions.fetch-provider-logos]
verify_jwt = false

[functions.import-resources]
verify_jwt = false
